name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install updater dependencies
      run: cd updater && npm ci
      
    - name: Build main application
      run: npm run build:win
      
    - name: Build updater
      run: npm run build-updater
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          updater/dist/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 